version: "3"
services:
  kafka:
    image: "bitnami/kafka:3.6.0"
    container_name: linkme-kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CREATE_TOPICS=linkme_binlog:3:1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      # 注意下述id需改为你当前运行kafka的服务器的实际ip，如果是本机则改为localhost
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  db:
    image: mysql:8.0
    container_name: linkme-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkme
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    container_name: linkme-redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--bind"
      - "0.0.0.0"
      - "--protected-mode"
      - "no"
      - "--port"
      - "6379"
  mongo:
    image: mongo:latest
    container_name: linkme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
