server:
  addr: ":9999"

jwt:
  auth_key: "ebe3vxIP7sblVvUHXb7ZaiMPuz4oXo0l"
  refresh_key: "sadfkhjlkkljKFJDSLAFUDASLFJKLjfj113d2"
  issuer: "K5mBPBYNQeNWEBvCTE5msog3KSGTdhmI"
  auth_expire: 30 # 分钟
  refresh_expire: 150 # 小时

log:
  dir: "logs"
  
db:
  # dsn: "root:v6SxhWHyZC7S@tcp(mysql:3306)/linkme?charset=utf8mb4&parseTime=True&loc=Local"
  dsn: "root:v6SxhWHyZC7S@tcp(192.168.5.11:33306)/linkme?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  # addr: "redis:6379"
  addr: "192.168.5.11:36379"
  password: "v6SxhWHyZC7S"

kafka:
  # addr: "kafka:9092"
  addr: "192.168.5.11:9092"

es:
  addr: "http://192.168.5.11:9200"

sms:
  tencent:
    secretId: ""
    secretKey: ""
    endPoint: ""
    smsID: ""
    sign: ""
    templateID: ""

ark_api:
  key: "b3977816-2a07-44df-9fe2-4ec02224e147"