db:
  dsn: "root:root@tcp(localhost:3306)/linkme"
redis:
  addr: "localhost:6379" # 公网redis地址
log:
  filepath: "logs/linkme.json"
mongodb:
  addr: "mongodb://localhost:27017"
kafka:
  addr: "localhost:9092"
sms:
  tencent:
    secretId: ""
    secretKey: ""
    endPoint: ""
    smsID: ""
    sign: ""
    templateID: ""
